### ISSUE TITLE
8.0.1 doesn't build on web

### ISSUE THREAD

**Issue by anthonymoretti** [Lyokone/flutterlocation#1031]
**Describe the bug**

If I try to build on web with 8.0.1 I get this error:

```
Launching lib/main.dart on Chrome in debug mode...
../../../.pub-cache/hosted/pub.dev/location_web-6.0.0/lib/location_web.dart:25:16: Error: The method 'LocationWebPlugin.changeSettings' has fewer named arguments than those of overridden method 'LocationPlatform.changeSettings'.
location_web.dart:25
  Future<bool> changeSettings({
               ^
../../../.pub-cache/hosted/pub.dev/location_platform_interface-6.0.1/lib/location_platform_interface.dart:44:16: Context: This is the overridden method ('changeSettings').
location_platform_interface.dart:44
  Future<bool> changeSettings({
               ^
Failed to compile application.

Exited (1).
```

If I build with 8.0.0 there are no issues. I've tried running `flutter clean`.

**Expected behavior**

8.0.1 builds on web in the same manner as 8.0.0.

**Tested on:**

 - Chrome

**Comment by mauriziopinotti** [comment]
The maintainer just needs to bump the version of location_web and publish it un pub.dev, as the latest code in the repo is already correct (see commit https://github.com/Lyokone/flutterlocation/commit/f1fa51b7b46724ca481eb14b5a97fcea42230093)

Meanwhile, it can be fixed with a dependency override:

```yaml
dependency_overrides:
  # Waiting for https://github.com/Lyokone/flutterlocation/issues/1031
  location_web:
    git:
      url: https://github.com/Lyokone/flutterlocation
      path: packages/location_web
      ref: location-v8.0.1
```
