### ISSUE TITLE
Updating from 8.0.0 to 8.0.1 breaks my code

### ISSUE THREAD

**Issue by mulderpf** [Lyokone/flutterlocation#1032]
**Describe the bug**
When I run all my tests using location 8.0.0, everything works fine.  When I update to 8.0.1, it breaks with the following:
```
../../../.pub-cache/hosted/pub.dev/location-8.0.1/lib/location.dart:42:7: Error: No named parameter with the name
'pausesLocationUpdatesAutomatically'.
      pausesLocationUpdatesAutomatically: pausesLocationUpdatesAutomatically,
```

**Expected behavior**
An update of a minor version (e.g. 8.0.0 to 8.0.1 should not break any code)

**Tested on:**
 - I only ran my test suite and it already fails - I am unable to build using 8.0.1.

**Other plugins:**
 - Nothing else could break it - I test using a fixed version of 8.0.0 and everything works, when I test using 8.0.1, some of my tests start failing due to the reason given above.

**Comment by BabarBobtail** [comment]
Facing same issue

**Comment by bartekpacia** [comment]
Hi, I released a new version of `location_web`, please `flutter pub upgrade` + `flutter pub get` and say if it helps

**Comment by Mohammad-Abureesh** [comment]
> Hi, I released a new version of `location_web`, please `flutter pub upgrade` + `flutter pub get` and say if it helps

I don’t see any new branch or tag on location_web after location-v8.0.1. Were you referring to the same tag, or is there another one I might have missed?

**Comment by Mohammad-Abureesh** [comment]
As @vonweird  mentioned in the comments, the `pausesLocationUpdatesAutomatically ` issue originates from the `location_platform_interface ` package.

To work around this until a new version of the location package is published, you can add the following override to your pubspec.yaml:

```
dependency_overrides:
  # Waiting for https://github.com/Lyokone/flutterlocation/issues/1031
  location_platform_interface: ^6.0.1
  location_web:
    git:
      url: https://github.com/Lyokone/flutterlocation
      path: packages/location_web
      ref: location-v8.0.1
```
