### ISSUE TITLE
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. >

### ISSUE THREAD

**Issue by FaanB** [Lyokone/flutterlocation#163]
**Describe the bug**
When I do 'flutter run' without "  location: ^2.3.5" in my pubspec.yaml it starts fine,
When I run it with that I get:

> FAILURE: Build failed with an exception.                                
>                                                                         
> * What went wrong:                                                      
> Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> > The library com.google.android.gms:play-services-basement is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 16.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
>                                                                         
> * Try:                                                                  
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>                                                                         
> * Get more help at https://help.gradle.org                              
> 

Changing this line in .../flutter/.pub-cache/hosted/pub.dartlang.org/location-2.3.5/android/build.gradle fixed the problem, it now compiles.
```
dependencies {
    api 'com.google.android.gms:play-services-location:16.+'
}
```
```
dependencies {
    api 'com.google.android.gms:play-services-location:15.+'
}
```

That probably means I have to change my own 15 to 16, but I have no idea where or how to do that.

**Tested on:**
 - Android, API Level 19 real device
 - iOS, Version 12, simulator 

**Other plugins:**
 - List of others Flutter plugins that could interfere
```
dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path_provider: ^0.4.1
  rxdart: ^0.18.0  
  charts_flutter: ^0.4.0
  #image_picker: ^0.4.10
  transparent_image: ^0.1.0
  http: ^0.12.0
  shared_preferences: ^0.5.1+1
  location: ^2.3.5
  #package_info: any
```

**Additional logs**

You asked for a template but I don't know what that refers to sorry.
