### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by hetkpatel** [Lyokone/flutterlocation#70]
I am trying to run my flutter project on my Samsung S7 but I keep getting the following error.

```
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.`

Because veggie_diet depends on location >=1.0.1 which requires SDK version <2.0.0, version solving failed.

pub get failed (1)
```
My guess is it might be something wrong with my `pubspec.yaml`:

```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  image_picker: ^0.4.2
  url_launcher: ^3.0.0
  firebase_auth: 0.5.9
  location: ^1.3.4
  firebase_database: ^0.4.6
  firebase_storage: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
```

I also have no errors when running `flutter doctor`
```
[✓] Flutter (Channel master, v0.5.9-pre.80, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.5.9-pre.80 at /Users/hetpatel/Documents/development/flutter
    • Framework revision 809721d0ee (2 days ago), 2018-08-17 18:34:05 -0700
    • Engine revision 4ee648914f
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Volumes/HPBD2017/AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • SM G930T • fc204956 • android-arm64 • Android 8.0.0 (API 26)
```
