### ISSUE TITLE
serviceEnabled() goes into an infinite loop when User disabling Precise location on IOS

### ISSUE THREAD

**Issue by mohammadshrahi** [Lyokone/flutterlocation#704]
**Describe the bug**
serviceEnabled()  goes into an infinite loop when the User disabling Precise location on IOS
I tried to clean the project and restart but still getting the same results
**Expected behavior**
If an IOS user disables precise location from the app settings then serviceEnabled() should work fine.

**Tested on:**
 - iOS, Version 15.3.1, real device

**Other plugins:**
 - List of others Flutter plugins that could interfere
 ```
 adaptive_dialog: ^0.10.0+5
  adjust_sdk: ^4.29.1
  algolia:
    git: https://github.com/Rart3001/dart_algolia
  cached_network_image: ^3.0.0-nullsafety
  carousel_slider: ^4.0.0-nullsafety.0
  clock: ^1.1.0
  collection: ^1.15.0
  connectivity_plus: ^2.0.2
  cupertino_icons: ^1.0.2
  device_info: ^2.0.0
  device_proxy:
    git: https://github.com/zaralockheart/device_proxy
  devicelocale: ^0.4.3
  diacritic: ^0.1.3
  dio: ^4.0.4
  email_validator: ^2.0.1
  emarsys_sdk: ^1.2.1
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  faker: ^2.0.0
  firebase_analytics: ^9.1.2
  firebase_crashlytics: ^2.5.3
  firebase_remote_config: ^2.0.2
  flash: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_html: ^2.2.1
  flutter_keyboard_visibility: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_secure_storage: ^5.0.2
  flutter_slidable: ^0.6.0
  flutter_staggered_grid_view: ^0.6.0
  flutter_svg: ^0.22.0
  flutter_webview_plugin: ^0.4.0
  gql_dio_link: ^0.1.0
  graphql: ^5.0.0-nullsafety.1+readmefix
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.0
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  kiwi: ^3.0.0
  kiwi_generator: ^3.0.1
  location: ^4.3.0
  logger: ^1.1.0
  luhn: ^1.0.1
  mask_text_input_formatter: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  money2: ^2.2.1
  package_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.1
  permission_handler: ^6.0.1
  photo_view: ^0.12.0
  readmore: ^2.1.0
  recase: ^4.0.0
  rive: ^0.7.28
  scroll_to_index: ^2.0.0
  sealed_unions: ^3.0.3+1
  share_plus: ^3.1.0
  shared_preferences: ^2.0.8
  simple_animations: ^3.0.3
  string_validator: ^0.3.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.2
  version_banner: ^1.0.0-nullsafety.0
  vibration: ^1.7.4-nullsafety.0
  webview_flutter: ^2.8.0
  youtube_player_iframe: ^2.2.2
```

**Additional logs**

There is no any additional logs
