### ISSUE TITLE
Build failed on Android (version 4.3.0)

### ISSUE THREAD

**Issue by burekas7** [Lyokone/flutterlocation#712]
**Describe the bug**
I'm using these packages:
```
location: ^4.3.0
firebase_core: ^1.14.1
firebase_auth: ^3.3.14
cloud_firestore: ^3.1.12
```

When I'm trying to build an app I'm getting these errors:
- Execution failed for task ':location:compileDebugKotlin'.
- Class 'FlutterLocationService' is not abstract and does not implement abstract member
- 'onRequestPermissionsResult' overrides nothing

The full error in the console log:
https://paste.ubuntu.com/p/ZGt7gpQDDs/plain/

I have already try the "flutter clean", upgrade packages, changing to older package versions, trying different sdk versions, kotlin versions etc..

**Expected behavior**
It was working and built few weeks ago.

**Tested on:**
- Flutter Channel beta, 2.12.0-4.1.pre
- Android, API Level 28, simulator 
- Android, Samsung Galaxy S8, real device

**Other plugins:**
```
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  location: ^4.3.0
  flutter_local_notifications: ^9.4.0
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.1.12
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
```
