### ISSUE TITLE
Support Android Gradle plugin 7.3.0

### ISSUE THREAD

**Issue by asaarnak** [Lyokone/flutterlocation#762]
**Since Android Gradle plugin 7.3.0 minimum Kotlin plugin version is 1.5.20** 
https://developer.android.com/studio/releases/gradle-plugin#min-kotlin-version

**Building app gives error:**
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':location' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20

**Comment by deep1931** [comment]
Hello,
Have you found any solution facing the same issue...

**Comment by asaarnak** [comment]
Currently staying on 7.2.2 and waiting for dependencies to catch up with Kotlin version.

**Comment by kostadin24** [comment]
Does 7.2.2 support Android13?

**Comment by dsgriffin** [comment]
any fix for this?

**Comment by Bhat015** [comment]
Why is this not resolved yet?

**Comment by asaarnak** [comment]
Created temporary workaround for me, if anyone want's to use it.
```yaml
  location:
    git:
      url: git@github.com:asaarnak/flutterlocation.git
      ref: patch-1
      path: packages/location
```
