### ISSUE TITLE
Can you please release 5.0.0 as facing lot of issues with 4.4.0

### ISSUE THREAD

**Issue by adityarath302** [Lyokone/flutterlocation#816]
We are actually dependent on this plugin for background processing and notification. Please release the next stable version with the changes as many build and stability issues are there in 4.4.0.It would help a lot.

**Comment by Priahi** [comment]
^^^^

**Comment by 781flyingdutchman** [comment]
I had the same issue and believe the author is focused on V5 and not currently maintaining V4. I forked the V4 version and updated the gradle plugin version.  Until the author fixes this you can use my fork in the pubspec.yaml:
```
location:
    git:
      url: git@github.com:781flyingdutchman/flutterlocation.git
      ref: V4 
```

**Comment by Priahi** [comment]
Thanks for your help @781flyingdutchman . I am facing issues in installing your package. The ssh URL didn't work so I went with the HTTP - which returns this issue. Seems your fork is missing the pubspec.yaml file:
<img width="998" alt="image" src="https://user-images.githubusercontent.com/31714266/229598833-1e512d41-4fc9-4759-9d84-9e5f746ebde6.png">

**Comment by 781flyingdutchman** [comment]
Sorry, I didn't get this right:
```
  location:
    git:
      url: https://github.com/781flyingdutchman/flutterlocation.git
      ref: V4
      path: packages/location
```
I'll edit the original comment
