### ISSUE TITLE
fix: Not working Gradle 7.4.2 version

### ISSUE THREAD

**Issue by hmshohrab** [Lyokone/flutterlocation#827]
![image_2023_03_28T08_09_12_767Z-1](https://user-images.githubusercontent.com/47864478/228171771-f766e9bd-f2a7-43b6-9cbe-6e29b6b3edb8.png)

**Comment by moesaid** [comment]
same issue

**Comment by 781flyingdutchman** [comment]
I had the same issue and believe the author is focused on V5 and not currently maintaining V4. I forked the V4 version and updated the gradle plugin version.  Until the author fixes this you can use my fork in the pubspec.yaml:
```
location:
    git:
      url: git@github.com:781flyingdutchman/flutterlocation.git
      ref: V4 
```

**Comment by 781flyingdutchman** [comment]
You'll have to set up [ssh keys](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)  to access GitHub. The repository is public

**Comment by 781flyingdutchman** [comment]
Actually, i think you can use:
```
location:
    git:
      url: git://github.com/781flyingdutchman/flutterlocation.git
      ref: V4 
```

without the need for ssh keys

**Comment by 781flyingdutchman** [comment]
Apologies, I didn't get this right- here's what works for me:
```
  location:
    git:
      url: https://github.com/781flyingdutchman/flutterlocation.git
      ref: V4
      path: packages/location
```

I'll edit the original comment
