### ISSUE TITLE
getLocation() and onLocationChanged() blocks with no response.

### ISSUE THREAD

**Issue by zedan185** [Lyokone/flutterlocation#83]
Now I added the package in my pubspec.yaml in the following way:

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  progress_hud:
     git: https://github.com/LampeMW/progress_hud/
  crypto: any
  validate: "^1.6.0"
  json_annotation: ^0.2.4
  image_picker: "^0.4.1"
  after_layout: "^1.0.4"
  firebase_messaging: #0.2.1
  device_info: ^0.2.1
#  geolocator: '^2.0.1'
  location: 
    git: https://github.com/Lyokone/flutterlocation.git/
```
And I tried the following two ways - both of them block and never return
```

//This method blocks
  Map<String, double> location = await new Location().onLocationChanged().single;

//This method also blocks and never continues
  currentLocation  = await  myLocation.Location().getLocation();
```

Here is the output from my flutter doctor

[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.6.0 at /Users/admin/Flutter/flutter
    • Framework revision 9299c02cf7 (8 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/hsheikh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 24.0.2
    • Dart plugin version 181.4445.29

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!

Any suggestions on what might be happening here. I tried the package geolocator and it behaves the same way except sometimes it would work (by not blocking). Why is this happening and how can I fix this ?
