### ISSUE TITLE
Compilation error location 4.4.0

### ISSUE THREAD

**Issue by TheLoveS** [Lyokone/flutterlocation#838]
Good afternoon,
location: ^4.4.0 in your repository in the original file
ext.kotlin_version = '1.7.20'
repositories {
        google()
        maven Central()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
(flutterlocation-master\packages\location\example\android\),
and I have
ext.kotlin_version = '1.4.20'
repositories in the same place {
        google()
        maven Central()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
How so, although version 4.4.0 swears at ext.kotlin_version = '1.4.20' during assembly
Help me fix the error

**Comment by elnurxf** [comment]
Sam here +1 spend 6 hours to figure it out, but no luck.

**Comment by Kanwarpalsingh1986** [comment]
Same problem

**Comment by elnurxf** [comment]
Tmp workaround:

```
  location:
    git:
      url: https://github.com/781flyingdutchman/flutterlocation.git
      ref: V4
      path: packages/location
```
