### ISSUE TITLE
Issue with location.requestService()

### ISSUE THREAD

**Issue by lightify97** [Lyokone/flutterlocation#887]
**Describe the bug**
In my app, I'm trying to make sure location services are enabled by constantly asking the user to enable location services (until the user enables). The problem is when the user denies the location service request the second time there's an exception. I'm also posting a video below so you can have a better context.

Correction: As you can see in the video I'm requesting permissions before the service is enabled. But I have tried to change the order and suddenly there are multiple dialogs that appear.

https://github.com/Lyokone/flutterlocation/assets/16276964/ba3f8f9d-2bfd-4a90-acb2-14c84b3391d5

**Expected behavior**
The location service dialog should keep opening until the user enables location services. 

**Tested on:**
 - Android, API Level 31, real device

**Other plugins:**
```
dependencies:
    flutter:
        sdk: flutter
    connectivity_plus: ^4.0.2
    pin_code_fields: ^8.0.1
    firebase_core: ^2.15.0
    firebase_auth: ^4.7.2
    cloud_firestore: ^4.8.4
    firebase_storage: ^11.2.5
    provider: ^6.0.5
    shared_preferences: ^2.2.0
    firebase_app_check: ^0.1.5+1
    intl: ^0.18.1
    image_picker: ^1.0.2
    iconsax: ^0.0.8
    h3_flutter: ^0.6.6
    google_maps_flutter: ^2.4.0
    country_currency_pickers: ^3.0.0
    material_color_utilities: ^0.2.0
    flutter_config: ^2.0.2
    location: ^5.0.3
    simple_ripple_animation: ^0.0.7
    cached_network_image: ^3.2.3
    uuid: ^3.0.7
    flutter_polyline_points: ^1.0.0
    socket_io_client: ^2.0.3+1
    dio: ^5.3.2
```

**Additional logs**
This is the exception that occurs.

```shell
D/AndroidRuntime(26052): Shutting down VM
E/AndroidRuntime(26052): FATAL EXCEPTION: main
E/AndroidRuntime(26052): Process: com.drop, PID: 26052
E/AndroidRuntime(26052): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=Intent {  }} to activity {com.drop/com.drop.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(26052): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5571)
E/AndroidRuntime(26052): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5612)
E/AndroidRuntime(26052): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(26052): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(26052): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(26052): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
E/AndroidRuntime(26052): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(26052): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(26052): 	at android.app.ActivityThread.main(ActivityThread.java:8625)
E/AndroidRuntime(26052): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26052): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(26052): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime(26052): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(26052): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime(26052): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:268)
E/AndroidRuntime(26052): 	at com.lyokone.location.FlutterLocation.onActivityResult(FlutterLocation.java:183)
E/AndroidRuntime(26052): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:809)
E/AndroidRuntime(26052): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
E/AndroidRuntime(26052): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:872)
E/AndroidRuntime(26052): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:917)
E/AndroidRuntime(26052): 	at android.app.Activity.dispatchActivityResult(Activity.java:8550)
E/AndroidRuntime(26052): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5564)
E/AndroidRuntime(26052): 	... 11 more
I/Process (26052): Sending signal. PID: 26052 SIG: 9
Lost connection to device.
```
